import { Listing, WantedRequest } from "./types";

export const mockListings: Listing[] = [
  {
    id: "1",
    sellerId: "u1",
    sellerName: "Jean Pierre",
    sellerPhone: "+250788123456",
    sellerPhoneVerified: true,
    sellerDistrict: "Nyagatare",
    category: "cattle",
    title: "Friesian Cow",
    price: 1200000,
    district: "Nyagatare",
    sector: "Karangazi",
    images: [
      "https://images.unsplash.com/photo-1570042225831-d98fa7577f1e?w=800&q=80",
      "https://images.unsplash.com/photo-1516467508483-a7212febe31a?w=800&q=80",
    ],
    status: "active",
    views: 47,
    postedAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    breed: "Friesian",
    sex: "female",
    age: "4 years",
    weight: "450 kg",
    milkProduction: "18 litres/day",
    vaccinationStatus: "Up to date",
    purpose: "Dairy",
    description: "Healthy dairy cow. Excellent milk producer. Ready to sell.",
  },
  {
    id: "2",
    sellerId: "u2",
    sellerName: "Marie Claire",
    sellerPhone: "+250722345678",
    sellerPhoneVerified: true,
    sellerDistrict: "Kayonza",
    category: "goats",
    title: "Male Goat",
    price: 90000,
    district: "Kayonza",
    sector: "Murama",
    images: [
      "https://images.unsplash.com/photo-1524024973431-2ad916746881?w=800&q=80",
    ],
    status: "active",
    views: 23,
    postedAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    breed: "Saanen",
    sex: "male",
    age: "1 year",
    weight: "35 kg",
    vaccinationStatus: "Vaccinated",
  },
  {
    id: "3",
    sellerId: "u3",
    sellerName: "Emmanuel",
    sellerPhone: "+250733456789",
    sellerPhoneVerified: false,
    sellerDistrict: "Muhanga",
    category: "pigs",
    title: "Large White Pig",
    price: 180000,
    district: "Muhanga",
    sector: "Nyamabuye",
    images: [
      "https://images.unsplash.com/photo-1598456694914-7f6e2a2fa0e8?w=800&q=80",
    ],
    status: "active",
    views: 15,
    postedAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
    breed: "Large White",
    sex: "female",
    age: "8 months",
    weight: "75 kg",
    vaccinationStatus: "Vaccinated",
    purpose: "Breeding",
  },
  {
    id: "4",
    sellerId: "u4",
    sellerName: "Solange",
    sellerPhone: "+250782567890",
    sellerPhoneVerified: true,
    sellerDistrict: "Bugesera",
    category: "chickens",
    title: "Local Chickens",
    price: 8000,
    priceUnit: "each",
    quantity: 20,
    district: "Bugesera",
    sector: "Gashora",
    images: [
      "https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=800&q=80",
    ],
    status: "active",
    views: 61,
    postedAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
    chickenType: "local",
    age: "6 months",
    description: "Healthy local chickens, ready for sale. 20 available.",
  },
  {
    id: "5",
    sellerId: "u5",
    sellerName: "Alexis",
    sellerPhone: "+250755678901",
    sellerPhoneVerified: true,
    sellerDistrict: "Musanze",
    category: "eggs",
    title: "Fresh Eggs",
    price: 4500,
    priceUnit: "per tray",
    traysAvailable: 100,
    district: "Musanze",
    sector: "Muhoza",
    images: [
      "https://images.unsplash.com/photo-1587486913049-53fc88980cfc?w=800&q=80",
    ],
    status: "active",
    views: 89,
    postedAt: new Date(Date.now() - 1000 * 60 * 60 * 3).toISOString(),
    description: "Fresh eggs collected daily. 100 trays available.",
  },
  {
    id: "6",
    sellerId: "u6",
    sellerName: "Chantal",
    sellerPhone: "+250788789012",
    sellerPhoneVerified: true,
    sellerDistrict: "Gicumbi",
    category: "milk",
    title: "Fresh Milk",
    price: 700,
    priceUnit: "per litre",
    litresAvailable: 50,
    milkAvailability: "daily",
    district: "Gicumbi",
    sector: "Byumba",
    images: [
      "https://images.unsplash.com/photo-1563636619-e9143da7973b?w=800&q=80",
    ],
    status: "active",
    views: 34,
    postedAt: new Date(Date.now() - 1000 * 60 * 60 * 1).toISOString(),
    description: "Fresh cow milk available daily. 50 litres per day.",
  },
  {
    id: "7",
    sellerId: "u7",
    sellerName: "Patrick",
    sellerPhone: "+250722890123",
    sellerPhoneVerified: false,
    sellerDistrict: "Huye",
    category: "sheep",
    title: "Dorper Sheep",
    price: 120000,
    quantity: 5,
    district: "Huye",
    sector: "Tumba",
    images: [
      "https://images.unsplash.com/photo-1484557985045-edf25e08da73?w=800&q=80",
    ],
    status: "active",
    views: 18,
    postedAt: new Date(Date.now() - 1000 * 60 * 60 * 48).toISOString(),
    breed: "Dorper",
    sex: "female",
    age: "2 years",
    weight: "40 kg",
    vaccinationStatus: "Vaccinated",
  },
  {
    id: "8",
    sellerId: "u8",
    sellerName: "Diane",
    sellerPhone: "+250733901234",
    sellerPhoneVerified: true,
    sellerDistrict: "Rwamagana",
    category: "honey",
    title: "Pure Honey",
    price: 15000,
    priceUnit: "per kg",
    quantity: 30,
    district: "Rwamagana",
    sector: "Munyiginya",
    images: [
      "https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=800&q=80",
    ],
    status: "active",
    views: 42,
    postedAt: new Date(Date.now() - 1000 * 60 * 60 * 6).toISOString(),
    description: "Pure natural honey. 30 kg available.",
  },
  {
    id: "9",
    sellerId: "u9",
    sellerName: "Innocent",
    sellerPhone: "+250788012345",
    sellerPhoneVerified: true,
    sellerDistrict: "Rubavu",
    category: "rabbits",
    title: "Rabbits",
    price: 12000,
    priceUnit: "each",
    quantity: 15,
    district: "Rubavu",
    sector: "Gisenyi",
    images: [
      "https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?w=800&q=80",
    ],
    status: "active",
    views: 29,
    postedAt: new Date(Date.now() - 1000 * 60 * 60 * 12).toISOString(),
    breed: "New Zealand White",
    age: "4 months",
  },
  {
    id: "10",
    sellerId: "u1",
    sellerName: "Jean Pierre",
    sellerPhone: "+250788123456",
    sellerPhoneVerified: true,
    sellerDistrict: "Nyagatare",
    category: "cattle",
    title: "Young Bull",
    price: 850000,
    district: "Nyagatare",
    sector: "Karangazi",
    images: [
      "https://images.unsplash.com/photo-1516467508483-a7212febe31a?w=800&q=80",
    ],
    status: "sold",
    views: 102,
    postedAt: new Date(Date.now() - 1000 * 60 * 60 * 72).toISOString(),
    breed: "Ankole",
    sex: "male",
    age: "18 months",
    weight: "320 kg",
    purpose: "Breeding",
  },
];

export const mockWantedRequests: WantedRequest[] = [
  {
    id: "w1",
    buyerId: "b1",
    buyerName: "Restaurant Chez Lando",
    buyerPhone: "+250788200100",
    buyerDistrict: "Kigali",
    category: "goats",
    title: "Looking for 10 goats",
    quantity: "10",
    budget: "Negotiable",
    neededBy: "2026-09-05",
    description: "Need healthy goats for restaurant. Will consider various breeds.",
    postedAt: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    status: "open",
  },
  {
    id: "w2",
    buyerId: "b2",
    buyerName: "Musanze Butchery",
    buyerPhone: "+250788200200",
    buyerDistrict: "Musanze",
    category: "cattle",
    title: "Looking for 5 cows",
    quantity: "5",
    budget: "5,000,000 RWF total",
    neededBy: "2026-09-15",
    description: "Seeking beef cattle for butchery. Must weigh at least 300 kg.",
    postedAt: new Date(Date.now() - 1000 * 60 * 60 * 8).toISOString(),
    status: "open",
  },
  {
    id: "w3",
    buyerId: "b3",
    buyerName: "Alexis Mutabazi",
    buyerPhone: "+250788200300",
    buyerDistrict: "Musanze",
    category: "eggs",
    title: "Looking for 100 trays of eggs",
    quantity: "100 trays",
    neededBy: "2026-08-30",
    description: "Weekly supply preferred. Must be fresh.",
    postedAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    status: "open",
  },
  {
    id: "w4",
    buyerId: "b4",
    buyerName: "Hotel des Mille Collines",
    buyerPhone: "+250788200400",
    buyerDistrict: "Nyarugenge",
    category: "milk",
    title: "Daily fresh milk supply needed",
    quantity: "100 litres/day",
    budget: "Market price",
    description: "Looking for reliable daily supply of fresh milk. Prefer Kigali area.",
    postedAt: new Date(Date.now() - 1000 * 60 * 60 * 24).toISOString(),
    status: "open",
  },
  {
    id: "w5",
    buyerId: "b5",
    buyerName: "Jean Claude",
    buyerPhone: "+250788200500",
    buyerDistrict: "Kayonza",
    category: "pigs",
    title: "Piglets wanted",
    quantity: "20 piglets",
    budget: "Negotiable",
    neededBy: "2026-09-20",
    description: "Looking for healthy piglets for fattening.",
    postedAt: new Date(Date.now() - 1000 * 60 * 60 * 36).toISOString(),
    status: "open",
  },
];

export const mockUser = {
  id: "u1",
  name: "Jean Pierre",
  email: "jean@example.com",
  phone: "+250788123456",
  district: "Nyagatare",
  userType: "farmer" as const,
  phoneVerified: true,
  createdAt: "2025-01-15T00:00:00.000Z",
};
